# permissions for end users to edit dbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbackup-editor-role
rules:
- apiGroups:
  - batch.k8s.htw-berlin.de
  resources:
  - dbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.k8s.htw-berlin.de
  resources:
  - dbackups/status
  verbs:
  - get
