
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.k8s.htw-berlin.de
  resources:
  - dbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.k8s.htw-berlin.de
  resources:
  - dbackups/finalizers
  verbs:
  - update
- apiGroups:
  - batch.k8s.htw-berlin.de
  resources:
  - dbackups/status
  verbs:
  - get
  - patch
  - update
